services:
  - type: web
    name: jochat-preview
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENROUTER_API_KEY
        sync: false
